server:
  port: 8084

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/br_db
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  security:
    enabled:false

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

#backend:
#  api:
#    url:
#      pos-sales: http://localhost:8080/api/pos-sales/save